/*
    author: Paola A Buitrago @lolapaola
    credit: Joel W. King  @joelwking

    usage:

      Provider definition: A provider is responsible for understanding API interactions and exposing resources.
      Providers are downloaded when issuing a  `terraform init`. The `versions.tf` may be automatically generated by
      the `terraform init` command. This file specifies the source and version of the provider.

      We are referencing input variables the username, password and region. These values are defined in:

         - as a default value in `variables.tf` (region)
         - and as an environment variable on the host (access_key and secret_key)

      This use case utilizes the AWS provider, which interacts with resources AWS EC2.

    references:
      - https://www.terraform.io/docs/configuration/providers.html
      - https://gitlab.com/joelwking/terraform_aci

*/

provider "aws" {
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
  region = var.aws_region
}
